vich_uploader:
    db_driver: orm

    mappings:
        plats:
            uri_prefix: /images/plats
            # Dossier d'upload des images
            upload_destination: '%kernel.project_dir%/public/images/plats'
            # Type d'encodage des noms des images
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

    metadata:
        type: attribute